Rewrite and name change.

diff --git a/tools/mpk-build b/tools/mpk-build
--- a/tools/mpk-build
+++ b/tools/mpk-build
@@ -1,6 +1,3 @@
-#! /bin/sh
-. mp-functions
-
 build_source()
 {
   : ${top_srcdir:=$name-$version}
@@ -9,8 +6,11 @@ build_source()
   pkg_instdir=$resultdir
 
   if [ ! -d $pkg_builddir ]; then
-    echo "$0: Please unpack the source first."
-    exit 1
+    $mpk unpack $pkg
+    if [ ! -d $pkg_builddir ]; then
+      echo >&2 "$(basename $0) build: Could not unpack $pkg"
+      exit 1
+    fi
   fi
   
   cd $pkg_builddir
@@ -61,21 +61,23 @@ do_configure()
     pkg_configure_opt="$pkg_configure_opt LDFLAGS=-L$pkg_instdir/lib"
   fi
   
-  echo 'Configuring...'
+  export PKG_CONFIG_LIBDIR=$resultdir/lib/pkgconfig
+
+  echo "Configuring $pkg..."
   mkdir -p ../logs
   ./configure $pkg_configure_opt > ../logs/configure.log
 }
 
 do_compile()
 {
-  echo 'Compiling...'
+  echo "Compiling $pkg..."
   mkdir -p ../logs
   make > ../logs/make.log
 }
 
 do_install()
 {
-  echo 'Installing...'
+  echo "Installing $pkg..."
   mkdir -p ../logs
   make install > ../logs/install.log
 }
@@ -98,11 +100,19 @@ success()
 }
 
 if [ -z "$1" ]; then
-  echo "Usage: $0 package-name"
+  echo "Usage: $(basename $0) build package-name"
   exit 1
 fi
-name=$1
+pkg=$1
 
-. $(get_recipe_name $name)
+if [ -z "$pkg" ]; then
+  echo "Usage: $(basename $0) build package-name ..."
+  exit 1
+fi
+
+recipe=$(get_recipe_name $pkg) || exit 1
+
+. $recipe
 
 build_source
+
